### ISSUE TITLE
Add Snyk to check for potential and known vulnerabilities in packages and codebase and set as a pre-condition for PRs, CI and deployment. [InfoSec]

### ISSUE THREAD

**Issue by saifali96** [arkhn/fhir-pipe#21]
Snyk is a free and open source tool to check for potential and known vulnerabilities and can be integrated to any GitHub repo and can be integrated into CI and automatically checks every PR for vulnerabilities.

It can be complimented/substituted by Whitsource, which is a similar opensource package.

I would suggest we add this to all Arkhn repos to ensure maximum security and compliance. 

We are using both of the above tools at all our repos. :)

**Comment by LaRiffle** [comment]
I think it is now enabled, (see open PRs), is this what you were mentioning?

**Comment by saifali96** [comment]
@LaRiffle yes! Exactly.

That's what I meant. Is it also enabled in the rest of repos on Arkhn?

**Comment by LaRiffle** [comment]
Yes it is, thanks!
