### ISSUE TITLE
New path for config.yml

### ISSUE THREAD

**Issue by LaRiffle** [arkhn/fhir-pipe#32]
### Context of the Issue

We have a new mechanism to find the path of the config file (see https://github.com/arkhn/fhir-pipe/blob/master/fhirpipe/config.py#L16), and it does not search the config.yml file present in the package

### Expected & current behavior

I expected the config.yml present in `/usr/local/lib/python3.7/site-packages/fhirpipe-0.1-py3.7.egg/fhirpipe` to be loaded

But `/app/config.yml` was loaded

Is it expected?

**Comment by simonvadee** [comment]
There is a new mechanism indeed. 

The configuration may be passed using `--config=/your/absolute/path` but if you do not specify any configuration, it is equivalent to passing `--config=config.yml` which results in searching for the configuration file in the current directory.

As you may have noticed, the configuration files (`config.yml` and `config_docker.yml`) have been moved to the root directory (they're not in `fhirpipe`anymore). When you run `fhirpipe-run` without any option (after doing `python setup.py install`), the configuration present in the package is selected by default. When you run it inside docker, the `docker_config.yml` is copied inside the container in the working directory (therefore at `/app/config.yml`, and it is selected by default when you run `fhirpipe-run` in the container. Note that you can always specify an other path for the configuratioin if you mount one at a different location.

I hope I've made things clearer. We can review this together at the office!
