### ISSUE TITLE
Investigate alternative to the current stack

### ISSUE THREAD

**Issue by simonvadee** [arkhn/fhir-pipe#35]
I feel that the current status of fhir-pipe is rather unstable, and by that I mean:
- not easy to debug
- project structure is hard to understand
- processing is slow and cannot scale
- test coverage is not optimal

I don't think it's a sane base to keep iterating on. This is not an urgent matter (because it currently works as expected) but we should start thinking about long term solution, since this is really at the hearth of arkhn solutions.

**Comment by Nabellaleen** [comment]
Could you list, for the "high level points" you mentioned, the technical details implying its ?
- Why is it hard to debug ?
- What do you mean by "project structure", which part are hard to articulate ?
- Which parts are slow / fast ?
...

**Comment by simonvadee** [comment]
Sure!
- not easy to debug
--> it is hard to reproduce an error when one occurs, because we don't know which resource caused the issue and we only have access to the python stacktrace, which is obviously not descriptive enough. I think we should be able to reproduce a single unit (step) of the ETL for a single resource and have detailed feedback over the result.
Also, (and this is more personal obviously), I think that statically typed languages are a lot more appropriate for this kind of job because the compiler prevents a lot of easy-to-catch errors and it forces the developer to produce more "structured" and less error-prone code.

- project structure is hard to understand
(WIP, will update later)

- processing is slow and cannot scale
(WIP, will update later)

- test coverage is not optimal
--> Self explanatory
